// components/RemoteButton.tsx
import {Property} from "csstype";
import BackgroundColor = Property.BackgroundColor;

interface IRemoteButton {
  name: String,
  color: String,
  icon: String,
  text: String,
  click: Function
}

export const RemoteButton = (props: IRemoteButton) => {
  return (
    <div style={{
      backgroundColor: props.color as BackgroundColor,
      fontSize: props.text?.length == 1 ? "22px" : "84%"
    }}
         className={"m-2 rounded-3xl w-16 h-16 flex justify-center items-center cursor-pointer shadow-sm shadow-white/50"}
         onClick={() => props.click(props.name)}
    >
      {props.icon ? <img src={`/symbols/${props.icon}`} alt={""}/> : null}
      {props.text ?? null}
    </div>
  )
}

RemoteButton.defaultProps = {
  color: "white",
  icon: null,
  text: null
}

// src/components/RemoteButton.svelte
<script lang="ts">
  export let name: string;
  export let color: string = "white";
  export let icon: string | undefined = undefined;
  export let text: string = "";
  export let click: Function;
</script>

<div
  style={`background-color: ${color}; font-size: ${text.length === 1 ? "22px" : "84%"}`}
  class="m-2 rounded-3xl w-16 h-16 flex justify-center items-center cursor-pointer shadow-sm shadow-white/50"
  on:click={() => click(name)}
>
  {#if icon}
    <img src={`assets/symbols/${icon}`} alt={""}/>
  {/if}

  {#if text}
    {text}
  {/if}
</div>
